name: FluidNC Release Builder

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'new branch'
        required: true
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v3
      - name: Create content
        run: |
          mkdir foo
          echo "this is a test" >foo/bar
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: foo
          repository-name: MitchBradley/MitchBradley.github.io
          ssh-key: ${{ secrets.GHP_DEPLOY_KEY }}
          branch: ${{ github.event.inputs.branch }}
          target-folder: foo1
